name: rosgraph_msgs
description: A ROS rosgraph_msgs message package for dartros
version: 0.0.2
repository: https://github.com/TimWhiting/rosgraph_msgs_dart

environment:
  sdk: ">=2.7.0 < 3.0.0"

dependencies:
  buffer: ^1.0.6
  dartros: ^0.0.1
  std_msgs: ^0.0.1
